name: Close Actions

on:
  issues:
    types: [ closed ]
  pull_request:
    types: [ closed ]

jobs:
  close-actions:
    name: Close actions
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
      actions: write

    steps:
      - name: Remove labels
        uses: IamPekka058/removeLabels@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "🚧 Work in Progress"

      - name: Delete branch caches
        if: github.event_name == 'pull_request'
        uses: Friedinger/DeleteBranchCaches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ref: "refs/pull/${{ github.event.pull_request.number }}/merge"
